/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM
	customers c
GROUP BY
	country
ORDER BY
	total_customers DESC;

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM
	customers c
GROUP BY
	gender
ORDER BY
	total_customers DESC;

-- Find total products by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM
	products p
GROUP BY
	category
ORDER BY
	total_products DESC;

-- What is the average costs in each category?
SELECT
	category,
	avg(cost) AS avg_costs
FROM
	products p
GROUP BY
	category
ORDER BY
	avg_costs DESC;

-- What is the total revenue generated for each category?
SELECT
	category,
	sum(sales_amount) AS total_revenue
FROM
	fact_sales fs
LEFT JOIN 
	products p ON
	fs.product_key = p.product_key
GROUP BY
	category
ORDER BY
	total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
	fs.customer_key,
	concat(first_name, ' ', last_name) AS customer_name,
	sum(sales_amount) AS total_revenue
FROM
	fact_sales fs
LEFT JOIN 
	customers c ON
	fs.customer_key = c.customer_key
GROUP BY
	fs.customer_key,
	concat(first_name, ' ', last_name)
ORDER BY
	total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
	country,
	sum(quantity) AS items_sold
FROM
	fact_sales fs
LEFT JOIN 
	customers c ON
	fs.customer_key = c.customer_key
GROUP BY
	country
ORDER BY
	items_sold DESC;
